version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - fullcycle-network

  app:
    build: ./app
    container_name: node_app
    volumes:
      - ./app:/usr/src/app
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=fullcycle
    depends_on:
      - db
    networks:
      - fullcycle-network

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=fullcycle
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - fullcycle-network

volumes:
  mysql_data:

networks:
  fullcycle-network:
    driver: bridge